class Constants {
    static ParticleInfo = {
        // Gauge bosons
        Photon:        { symbol:"γ",spin:1,isospin:[0,0,0,0,0],hypercharge:0,chirality_pct : .5,fill_color:"#FFD700",name:"Photon",antiparticle:"Photon",hadron:[],generation:null,parity:-1,C_parity:-1,G_parity:null,magnetic_moment:0,base_lifespan:Infinity,charge:0,mass:0,baryon:0,lepton:{e:0,m:0,t:0} },
        Gluon:         { symbol:"g",spin:1,isospin:[0,0,0,0,0],hypercharge:0,chirality_pct : .5,fill_color:"#FF4500",name:"Gluon",antiparticle:"Gluon",hadron:[],generation:null,parity:-1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:Infinity,charge:0,mass:0,baryon:0,lepton:{e:0,m:0,t:0} },
        WBosonPlus:    { symbol:"W⁺",spin:1,isospin:[0,0,1,1,1],hypercharge:0,chirality_pct : 0,fill_color:"#00BFFF",name:"WBosonPlus",antiparticle:"WBosonMinus",hadron:[],generation:null,parity:-1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:3e-25,charge:1,mass:80379,baryon:0,lepton:{e:0,m:0,t:0} },
        WBosonMinus:   { symbol:"W⁻",spin:1,isospin:[0,0,1,-1,-1],hypercharge:0,chirality_pct : 1,fill_color:"#1E90FF",name:"WBosonMinus",antiparticle:"WBosonPlus",hadron:[],generation:null,parity:-1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:3e-25,charge:-1,mass:80379,baryon:0,lepton:{e:0,m:0,t:0} },
        ZBoson:        { symbol:"Z",spin:1,isospin:[0,0,1,0,0],hypercharge:0,chirality_pct : .6,fill_color:"#A9A9A9",name:"ZBoson",antiparticle:"ZBoson",hadron:[],generation:null,parity:-1,C_parity:1,G_parity:null,magnetic_moment:0,base_lifespan:3e-25,charge:0,mass:91187.6,baryon:0,lepton:{e:0,m:0,t:0} },
        
        // Higgs
        Higgs:         { symbol:"H",spin:0,isospin:[0,0,1/2,-1/2,-1/2],hypercharge:0,chirality_pct : null,fill_color:"#EEE8AA",name:"Higgs",antiparticle:"Higgs",hadron:[],generation:null,parity:1,C_parity:1,G_parity:1,magnetic_moment:0,base_lifespan:1.6e-22,charge:0,mass:125100,baryon:0,lepton:{e:0,m:0,t:0} },
        
        // Leptons (generation, parity)
        Electron:      { symbol:"e⁻",spin:0.5,isospin:[0,0,1/2,-1/2,0],hypercharge:-1,chirality_pct : .5,fill_color:"#0000FF",name:"Electron",antiparticle:"Positron",hadron:[],generation:1,parity:1,C_parity:null,G_parity:null,magnetic_moment:-1.00115965218128,base_lifespan:Infinity,charge:-1,mass:0.511,baryon:0,lepton:{e:1,m:0,t:0} },
        Positron:      { symbol:"e⁺",spin:0.5,isospin:[0,0,1/2,1/2,0],hypercharge:-1,chirality_pct : .5,fill_color:"#1E90FF",name:"Positron",antiparticle:"Electron",hadron:[],generation:1,parity:1,C_parity:null,G_parity:null,magnetic_moment:1.00115965218128,base_lifespan:Infinity,charge:1,mass:0.511,baryon:0,lepton:{e:-1,m:0,t:0} },
        Muon:          { symbol:"μ⁻",spin:0.5,isospin:[0,0,1/2,-1/2,0],hypercharge:-1,chirality_pct : .5,fill_color:"#800080",name:"Muon",antiparticle:"AntiMuon",hadron:[],generation:2,parity:1,C_parity:null,G_parity:null,magnetic_moment:-1.00116592089,base_lifespan:2.2e-6,charge:-1,mass:105.7,baryon:0,lepton:{e:0,m:1,t:0} },
        AntiMuon:      { symbol:"μ⁺",spin:0.5,isospin:[0,0,1/2,1/2,0],hypercharge:-1,chirality_pct : .5,fill_color:"#8A2BE2",name:"AntiMuon",antiparticle:"Muon",hadron:[],generation:2,parity:1,C_parity:null,G_parity:null,magnetic_moment:1.00116592089,base_lifespan:2.2e-6,charge:1,mass:105.7,baryon:0,lepton:{e:0,m:-1,t:0} },
        Tau:           { symbol:"τ⁻",spin:0.5,isospin:[0,0,1/2,-1/2,0],hypercharge:-1,chirality_pct : .5,fill_color:"#DA70D6",name:"Tau",antiparticle:"AntiTau",hadron:[],generation:3,parity:1,C_parity:null,G_parity:null,magnetic_moment:-1.00117721,base_lifespan:2.9e-13,charge:-1,mass:1776.9,baryon:0,lepton:{e:0,m:0,t:1} },
        AntiTau:       { symbol:"τ⁺",spin:0.5,isospin:[0,0,1/2,1/2,0],hypercharge:-1,chirality_pct : .5,fill_color:"#BA55D3",name:"AntiTau",antiparticle:"Tau",hadron:[],generation:3,parity:1,C_parity:null,G_parity:null,magnetic_moment:1.00117721,base_lifespan:2.9e-13,charge:1,mass:1776.9,baryon:0,lepton:{e:0,m:0,t:-1} },
        
        // Neutrinos (generation, parity)
        NeutrinoE:     { symbol:"νₑ",spin:0.5,isospin:[0,0,1/2,1/2,0],hypercharge:-1,chirality_pct : 1,fill_color:"#00CED1",name:"NeutrinoE",antiparticle:"AntiNeutrinoE",hadron:[],generation:1,parity:1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:Infinity,charge:0,mass:0.0000022,baryon:0,lepton:{e:1,m:0,t:0} },
        AntiNeutrinoE: { symbol:"ν̄ₑ",spin:0.5,isospin:[0,0,1/2,-1/2,0],hypercharge:-1,chirality_pct : 0,fill_color:"#20B2AA",name:"AntiNeutrinoE",antiparticle:"NeutrinoE",hadron:[],generation:1,parity:1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:Infinity,charge:0,mass:0.0000022,baryon:0,lepton:{e:-1,m:0,t:0} },
        NeutrinoMu:    { symbol:"ν_μ",spin:0.5,isospin:[0,0,1/2,1/2,0],hypercharge:-1,chirality_pct : 1,fill_color:"#4682B4",name:"NeutrinoMu",antiparticle:"AntiNeutrinoMu",hadron:[],generation:2,parity:1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:Infinity,charge:0,mass:0.17,baryon:0,lepton:{e:0,m:1,t:0} },
        AntiNeutrinoMu:{ symbol:"ν̄_μ",spin:0.5,isospin:[0,0,1/2,-1/2,0],hypercharge:-1,chirality_pct : 0,fill_color:"#5F9EA0",name:"AntiNeutrinoMu",antiparticle:"NeutrinoMu",hadron:[],generation:2,parity:1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:Infinity,charge:0,mass:0.17,baryon:0,lepton:{e:0,m:-1,t:0} },
        NeutrinoTau:   { symbol:"ν_τ",spin:0.5,isospin:[0,0,1/2,1/2,0],hypercharge:-1,chirality_pct : 1,fill_color:"#483D8B",name:"NeutrinoTau",antiparticle:"AntiNeutrinoTau",hadron:[],generation:3,parity:1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:Infinity,charge:0,mass:18.2,baryon:0,lepton:{e:0,m:0,t:1} },
        AntiNeutrinoTau:{symbol:"ν̄_τ",spin:0.5,isospin:[0,0,1/2,-1/2,0],hypercharge:-1,chirality_pct : 0,fill_color:"#6A5ACD",name:"AntiNeutrinoTau",antiparticle:"NeutrinoTau",hadron:[],generation:3,parity:1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:Infinity,charge:0,mass:18.2,baryon:0,lepton:{e:0,m:0,t:-1} },
        
        // Quarks (generation, color charge not shown here but could be added)
        Up:            { symbol:"u",spin:0.5,isospin:[1/2,1/2,1/2,1/2,0],hypercharge:1/3,chirality_pct : .5,fill_color:"#A0522D",name:"Up",antiparticle:"AntiUp",hadron:[],generation:1,parity:1,C_parity:null,G_parity:null,magnetic_moment:1.852,base_lifespan:Infinity,charge:2/3,mass:2.2,baryon:1/3,lepton:{e:0,m:0,t:0} },
        AntiUp:        { symbol:"ū",spin:0.5,isospin:[1/2,-1/2,1/2,-1/2,0],hypercharge:-1/3,chirality_pct : .5,fill_color:"#8B4513",name:"AntiUp",antiparticle:"Up",hadron:[],generation:1,parity:1,C_parity:null,G_parity:null,magnetic_moment:-1.852,base_lifespan:Infinity,charge:-2/3,mass:2.2,baryon:-1/3,lepton:{e:0,m:0,t:0} },
        Down:          { symbol:"d",spin:0.5,isospin:[1/2,-1/2,1/2,-1/2,0],hypercharge:1/3,chirality_pct : .5,fill_color:"#B22222",name:"Down",antiparticle:"AntiDown",hadron:[],generation:1,parity:1,C_parity:null,G_parity:null,magnetic_moment:-0.972,base_lifespan:Infinity,charge:-1/3,mass:4.7,baryon:1/3,lepton:{e:0,m:0,t:0} },
        AntiDown:      { symbol:"d̄",spin:0.5,isospin:[1/2,1/2,1/2,1/2,0],hypercharge:-1/3,chirality_pct : .5,fill_color:"#DC143C",name:"AntiDown",antiparticle:"Down",hadron:[],generation:1,parity:1,C_parity:null,G_parity:null,magnetic_moment:0.972,base_lifespan:Infinity,charge:1/3,mass:4.7,baryon:-1/3,lepton:{e:0,m:0,t:0} },
        Strange:       { symbol:"s",spin:0.5,isospin:[0,0,0,0,0],hypercharge:-2/3,chirality_pct : .5,fill_color:"#228B22",name:"Strange",antiparticle:"AntiStrange",hadron:[],generation:2,parity:1,C_parity:null,G_parity:null,magnetic_moment:-0.613,base_lifespan:1e-8,charge:-1/3,mass:96,baryon:1/3,lepton:{e:0,m:0,t:0} },
        AntiStrange:   { symbol:"s̄",spin:0.5,isospin:[0,0,0,0,0],hypercharge:2/3,chirality_pct : .5,fill_color:"#32CD32",name:"AntiStrange",antiparticle:"Strange",hadron:[],generation:2,parity:1,C_parity:null,G_parity:null,magnetic_moment:0.613,base_lifespan:1e-8,charge:1/3,mass:96,baryon:-1/3,lepton:{e:0,m:0,t:0} },
        Charm:         { symbol:"c",spin:0.5,isospin:[0,0,0,0,0],hypercharge:4/3,chirality_pct : .5,fill_color:"#00BFFF",name:"Charm",antiparticle:"AntiCharm",hadron:[],generation:2,parity:1,C_parity:null,G_parity:null,magnetic_moment:0.404,base_lifespan:1e-12,charge:2/3,mass:1280,baryon:1/3,lepton:{e:0,m:0,t:0} },
        AntiCharm:     { symbol:"c̄",spin:0.5,isospin:[0,0,0,0,0],hypercharge:-4/3,chirality_pct : .5,fill_color:"#87CEEB",name:"AntiCharm",antiparticle:"Charm",hadron:[],generation:2,parity:1,C_parity:null,G_parity:null,magnetic_moment:-0.404,base_lifespan:1e-12,charge:-2/3,mass:1280,baryon:-1/3,lepton:{e:0,m:0,t:0} },
        Bottom:        { symbol:"b",spin:0.5,isospin:[0,0,0,0,0],hypercharge:-1/3,chirality_pct : .5,fill_color:"#FFD700",name:"Bottom",antiparticle:"AntiBottom",hadron:[],generation:3,parity:1,C_parity:null,G_parity:null,magnetic_moment:-0.066,base_lifespan:1.5e-12,charge:-1/3,mass:4180,baryon:1/3,lepton:{e:0,m:0,t:0} },
        AntiBottom:    { symbol:"b̄",spin:0.5,isospin:[0,0,0,0,0],hypercharge:1/3,chirality_pct : .5,fill_color:"#FFA500",name:"AntiBottom",antiparticle:"Bottom",hadron:[],generation:3,parity:1,C_parity:null,G_parity:null,magnetic_moment:0.066,base_lifespan:1.5e-12,charge:1/3,mass:4180,baryon:-1/3,lepton:{e:0,m:0,t:0} },
        Top:           { symbol:"t",spin:0.5,isospin:[0,0,0,0,0],hypercharge:4/3,chirality_pct : .5,fill_color:"#A52A2A",name:"Top",antiparticle:"AntiTop",hadron:[],generation:3,parity:1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:5e-25,charge:2/3,mass:173000,baryon:1/3,lepton:{e:0,m:0,t:0} },
        AntiTop:       { symbol:"t̄",spin:0.5,isospin:[0,0,0,0,0],hypercharge:-4/3,chirality_pct : .5,fill_color:"#800000",name:"AntiTop",antiparticle:"Top",hadron:[],generation:3,parity:1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:5e-25,charge:-2/3,mass:173000,baryon:-1/3,lepton:{e:0,m:0,t:0} },
        
        // Baryons (proton, neutron, lambda, sigma, xi, omega)
        Proton:        { symbol:"p",spin:0.5,isospin:[],hypercharge:1,chirality_pct : null,fill_color:"#FFC0CB",name:"Proton",antiparticle:"AntiProton",hadron:["Up","Up","Down"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:2.793,base_lifespan:Infinity,charge:1,mass:938.3,baryon:1,lepton:{e:0,m:0,t:0} },
        AntiProton:    { symbol:"p̄",spin:0.5,isospin:[],hypercharge:-1,chirality_pct : null,fill_color:"#FF69B4",name:"AntiProton",antiparticle:"Proton",hadron:["AntiUp","AntiUp","AntiDown"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:-2.793,base_lifespan:Infinity,charge:-1,mass:938.3,baryon:-1,lepton:{e:0,m:0,t:0} },
        Neutron:       { symbol:"n",spin:0.5,isospin:[],hypercharge:1,chirality_pct : null,fill_color:"#708090",name:"Neutron",antiparticle:"AntiNeutron",hadron:["Up","Down","Down"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:-1.913,base_lifespan:880,charge:0,mass:939.6,baryon:1,lepton:{e:0,m:0,t:0} },
        AntiNeutron:   { symbol:"n̄",spin:0.5,isospin:[],hypercharge:-1,chirality_pct : null,fill_color:"#778899",name:"AntiNeutron",antiparticle:"Neutron",hadron:["AntiUp","AntiDown","AntiDown"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:1.913,base_lifespan:880,charge:0,mass:939.6,baryon:-1,lepton:{e:0,m:0,t:0} },
        Lambda:        { symbol:"Λ⁰",spin:0.5,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#F5DEB3",name:"Lambda",antiparticle:"AntiLambda",hadron:["Up","Down","Strange"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:-0.613,base_lifespan:2.6e-10,charge:0,mass:1115.7,baryon:1,lepton:{e:0,m:0,t:0} },
        AntiLambda:    { symbol:"Λ̄⁰",spin:0.5,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#DEB887",name:"AntiLambda",antiparticle:"Lambda",hadron:["AntiUp","AntiDown","AntiStrange"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:0.613,base_lifespan:2.6e-10,charge:0,mass:1115.7,baryon:-1,lepton:{e:0,m:0,t:0} },
        SigmaPlus:     { symbol:"Σ⁺",spin:0.5,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#D2691E",name:"SigmaPlus",antiparticle:"AntiSigmaMinus",hadron:["Up","Up","Strange"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:2.458,base_lifespan:0.8e-10,charge:1,mass:1189.4,baryon:1,lepton:{e:0,m:0,t:0} },
        SigmaZero:     { symbol:"Σ⁰",spin:0.5,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#CD853F",name:"SigmaZero",antiparticle:"SigmaZero",hadron:["Up","Down","Strange"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:0.649,base_lifespan:7.4e-20,charge:0,mass:1192.6,baryon:1,lepton:{e:0,m:0,t:0} },
        SigmaMinus:    { symbol:"Σ⁻",spin:0.5,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#8B4513",name:"SigmaMinus",antiparticle:"AntiSigmaPlus",hadron:["Down","Down","Strange"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:-1.160,base_lifespan:1.5e-10,charge:-1,mass:1197.4,baryon:1,lepton:{e:0,m:0,t:0} },
        AntiSigmaPlus: { symbol:"Σ̄⁻",spin:0.5,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#D2B48C",name:"AntiSigmaPlus",antiparticle:"SigmaMinus",hadron:["AntiDown","AntiDown","AntiStrange"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:1.160,base_lifespan:1.5e-10,charge:1,mass:1197.4,baryon:-1,lepton:{e:0,m:0,t:0} },
        AntiSigmaMinus:{ symbol:"Σ̄⁺",spin:0.5,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#F4A460",name:"AntiSigmaMinus",antiparticle:"SigmaPlus",hadron:["AntiUp","AntiUp","AntiStrange"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:-2.458,base_lifespan:0.8e-10,charge:-1,mass:1189.4,baryon:-1,lepton:{e:0,m:0,t:0} },
        XiZero:        { symbol:"Ξ⁰",spin:0.5,isospin:[],hypercharge:-1,chirality_pct : null,fill_color:"#DAA520",name:"XiZero",antiparticle:"AntiXiZero",hadron:["Up","Strange","Strange"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:-1.250,base_lifespan:2.9e-10,charge:0,mass:1314.9,baryon:1,lepton:{e:0,m:0,t:0} },
        XiMinus:       { symbol:"Ξ⁻",spin:0.5,isospin:[],hypercharge:-1,chirality_pct : null,fill_color:"#B8860B",name:"XiMinus",antiparticle:"AntiXiPlus",hadron:["Down","Strange","Strange"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:-0.650,base_lifespan:1.6e-10,charge:-1,mass:1321.7,baryon:1,lepton:{e:0,m:0,t:0} },
        AntiXiZero:    { symbol:"Ξ̄⁰",spin:0.5,isospin:[],hypercharge:1,chirality_pct : null,fill_color:"#BDB76B",name:"AntiXiZero",antiparticle:"XiZero",hadron:["AntiUp","AntiStrange","AntiStrange"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:1.250,base_lifespan:2.9e-10,charge:0,mass:1314.9,baryon:-1,lepton:{e:0,m:0,t:0} },
        AntiXiPlus:    { symbol:"Ξ̄⁺",spin:0.5,isospin:[],hypercharge:1,chirality_pct : null,fill_color:"#FFD700",name:"AntiXiPlus",antiparticle:"XiMinus",hadron:["AntiUp","AntiStrange","AntiStrange"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:0.650,base_lifespan:1.6e-10,charge:1,mass:1321.7,baryon:-1,lepton:{e:0,m:0,t:0} },
        OmegaMinus:    { symbol:"Ω⁻",spin:1.5,isospin:[],hypercharge:-2,chirality_pct : null,fill_color:"#BDB76B",name:"OmegaMinus",antiparticle:"AntiOmegaPlus",hadron:["Strange","Strange","Strange"],generation:null,parity:1,C_parity:null,G_parity:null,magnetic_moment:-2.02,base_lifespan:0.82e-10,charge:-1,mass:1672.5,baryon:1,lepton:{e:0,m:0,t:0} },
        
        // Mesons (quark-antiquark)
        PionPlus:      { symbol:"π⁺",spin:0,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#D3D3D3",name:"PionPlus",antiparticle:"PionMinus",hadron:["Up","AntiDown"],generation:null,parity:-1,C_parity:null,G_parity:1,magnetic_moment:0,base_lifespan:2.6e-8,charge:1,mass:139.6,baryon:0,lepton:{e:0,m:0,t:0} },
        PionMinus:     { symbol:"π⁻",spin:0,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#A9A9A9",name:"PionMinus",antiparticle:"PionPlus",hadron:["Down","AntiUp"],generation:null,parity:-1,C_parity:null,G_parity:1,magnetic_moment:0,base_lifespan:2.6e-8,charge:-1,mass:139.6,baryon:0,lepton:{e:0,m:0,t:0} },
        Pion:          { symbol:"π⁰",spin:0,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#C0C0C0",name:"Pion",antiparticle:"Pion",hadron:["Up","AntiUp","Down","AntiDown"],generation:null,parity:-1,C_parity:1,G_parity:1,magnetic_moment:0,base_lifespan:8.4e-17,charge:0,mass:134.98,baryon:0,lepton:{e:0,m:0,t:0} },
        KaonPlus:      { symbol:"K⁺",spin:0,isospin:[],hypercharge:1,chirality_pct : null,fill_color:"#00FF00",name:"KaonPlus",antiparticle:"KaonMinus",hadron:["Up","AntiStrange"],generation:null,parity:-1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:1.24e-8,charge:1,mass:493.7,baryon:0,lepton:{e:0,m:0,t:0} },
        KaonMinus:     { symbol:"K⁻",spin:0,isospin:[],hypercharge:-1,chirality_pct : null,fill_color:"#ADFF2F",name:"KaonMinus",antiparticle:"KaonPlus",hadron:["Strange","AntiUp"],generation:null,parity:-1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:1.24e-8,charge:-1,mass:493.7,baryon:0,lepton:{e:0,m:0,t:0} },
        Kaon:          { symbol:"K⁰",spin:0,isospin:[],hypercharge:1,chirality_pct : null,fill_color:"#7FFF00",name:"Kaon",antiparticle:"Kaon",hadron:["Down","AntiStrange"],generation:null,parity:-1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:0.89e-10,charge:0,mass:497.6,baryon:0,lepton:{e:0,m:0,t:0} },
        Eta:           { symbol:"η",spin:0,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#F5DEB3",name:"Eta",antiparticle:"Eta",hadron:["Up","AntiUp","Down","AntiDown","Strange","AntiStrange"],generation:null,parity:-1,C_parity:1,G_parity:1,magnetic_moment:0,base_lifespan:5e-19,charge:0,mass:547.9,baryon:0,lepton:{e:0,m:0,t:0} },
        RhoPlus:       { symbol:"ρ⁺",spin:1,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#B0E0E6",name:"RhoPlus",antiparticle:"RhoMinus",hadron:["Up","AntiDown"],generation:null,parity:-1,C_parity:null,G_parity:-1,magnetic_moment:0,base_lifespan:4.5e-24,charge:1,mass:775.11,baryon:0,lepton:{e:0,m:0,t:0} },
        RhoMinus:      { symbol:"ρ⁻",spin:1,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#AFEEEE",name:"RhoMinus",antiparticle:"RhoPlus",hadron:["Down","AntiUp"],generation:null,parity:-1,C_parity:null,G_parity:-1,magnetic_moment:0,base_lifespan:4.5e-24,charge:-1,mass:775.11,baryon:0,lepton:{e:0,m:0,t:0} },
        Rho:           { symbol:"ρ⁰",spin:1,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#E0FFFF",name:"Rho",antiparticle:"Rho",hadron:["Up","AntiUp","Down","AntiDown"],generation:null,parity:-1,C_parity:-1,G_parity:-1,magnetic_moment:0,base_lifespan:4.4e-24,charge:0,mass:775.3,baryon:0,lepton:{e:0,m:0,t:0} },
        Omega:         { symbol:"ω",spin:1,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#FFE4B5",name:"Omega",antiparticle:"Omega",hadron:["Up","AntiUp","Down","AntiDown"],generation:null,parity:-1,C_parity:-1,G_parity:-1,magnetic_moment:0,base_lifespan:7.8e-23,charge:0,mass:782.7,baryon:0,lepton:{e:0,m:0,t:0} },
        Phi:           { symbol:"ϕ",spin:1,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#FFDAB9",name:"Phi",antiparticle:"Phi",hadron:["Strange","AntiStrange"],generation:null,parity:-1,C_parity:-1,G_parity:null,magnetic_moment:0,base_lifespan:1.5e-22,charge:0,mass:1019.5,baryon:0,lepton:{e:0,m:0,t:0} },
        Jpsi:          { symbol:"J/ψ",spin:1,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#4169E1",name:"Jpsi",antiparticle:"Jpsi",hadron:["Charm","AntiCharm"],generation:null,parity:-1,C_parity:-1,G_parity:null,magnetic_moment:0,base_lifespan:7.2e-21,charge:0,mass:3096.9,baryon:0,lepton:{e:0,m:0,t:0} },
        DMeson:        { symbol:"D⁰",spin:0,isospin:[],hypercharge:1,chirality_pct : null,fill_color:"#00FA9A",name:"DMeson",antiparticle:"DMeson",hadron:["Charm","AntiUp"],generation:null,parity:-1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:4.1e-13,charge:0,mass:1864.8,baryon:0,lepton:{e:0,m:0,t:0} },
        DMesonPlus:    { symbol:"D⁺",spin:0,isospin:[],hypercharge:1,chirality_pct : null,fill_color:"#3CB371",name:"DMesonPlus",antiparticle:"DMesonMinus",hadron:["Charm","AntiDown"],generation:null,parity:-1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:1.04e-12,charge:1,mass:1869.6,baryon:0,lepton:{e:0,m:0,t:0} },
        DMesonMinus:   { symbol:"D⁻",spin:0,isospin:[],hypercharge:-1,chirality_pct : null,fill_color:"#2E8B57",name:"DMesonMinus",antiparticle:"DMesonPlus",hadron:["Down","AntiCharm"],generation:null,parity:-1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:1.04e-12,charge:-1,mass:1869.6,baryon:0,lepton:{e:0,m:0,t:0} },
        BMeson:        { symbol:"B⁰",spin:0,isospin:[],hypercharge:-1,chirality_pct : null,fill_color:"#B8860B",name:"BMeson",antiparticle:"BMeson",hadron:["Down","AntiBottom"],generation:null,parity:-1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:1.5e-12,charge:0,mass:5279.6,baryon:0,lepton:{e:0,m:0,t:0} },
        BMesonPlus:    { symbol:"B⁺",spin:0,isospin:[],hypercharge:-1,chirality_pct : null,fill_color:"#CD853F",name:"BMesonPlus",antiparticle:"BMesonMinus",hadron:["Up","AntiBottom"],generation:null,parity:-1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:1.6e-12,charge:1,mass:5279.3,baryon:0,lepton:{e:0,m:0,t:0} },
        BMesonMinus:   { symbol:"B⁻",spin:0,isospin:[],hypercharge:1,chirality_pct : null,fill_color:"#DEB887",name:"BMesonMinus",antiparticle:"BMesonPlus",hadron:["Bottom","AntiUp"],generation:null,parity:-1,C_parity:null,G_parity:null,magnetic_moment:0,base_lifespan:1.6e-12,charge:-1,mass:5279.3,baryon:0,lepton:{e:0,m:0,t:0} },
        Upsilon:       { symbol:"Υ",spin:1,isospin:[],hypercharge:0,chirality_pct : null,fill_color:"#FFD700",name:"Upsilon",antiparticle:"Upsilon",hadron:["Bottom","AntiBottom"],generation:null,parity:-1,C_parity:-1,G_parity:null,magnetic_moment:0,base_lifespan:1.21e-20,charge:0,mass:9460.3,baryon:0,lepton:{e:0,m:0,t:0} }
        
        EtaPrime:      { symbol: "η'", spin: 0, isospin: [], hypercharge: 0, chirality_pct : null, fill_color: "#EEDD82",  name: "EtaPrime", antiparticle: "EtaPrime", hadron: ["Up","AntiUp","Down","AntiDown","Strange","AntiStrange"], generation: null,  parity: -1, C_parity: 1, G_parity: 1, magnetic_moment: 0,  base_lifespan: 3.3e-21, charge: 0, mass: 957.8, baryon: 0, lepton: {e:0,m:0,t:0}},
        KaonShort:     { symbol: "K_S^0", spin: 0, isospin: [], hypercharge: 1, chirality_pct : null, fill_color: "#7FFF00",  name: "KaonShort", antiparticle: "KaonShort", hadron: ["Down","AntiStrange"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: 8.95e-11, charge: 0, mass: 497.6, baryon: 0, lepton: {e:0,m:0,t:0}},
        KaonLong:      { symbol: "K_L^0", spin: 0, isospin: [], hypercharge: 1, chirality_pct : null, fill_color: "#32CD32",  name: "KaonLong", antiparticle: "KaonLong", hadron: ["Down","AntiStrange"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: 5.1e-8, charge: 0, mass: 497.6, baryon: 0, lepton: {e:0,m:0,t:0}},
        KaonStarPlus:  { symbol: "K*⁺", spin: 1, isospin: [], hypercharge: 1, chirality_pct : null, fill_color: "#00FF00",  name: "KaonStarPlus", antiparticle: "KaonStarMinus", hadron: ["Up","AntiStrange"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: 1.3e-23, charge: 1, mass: 891.7, baryon: 0, lepton: {e:0,m:0,t:0}},
        KaonStarMinus: { symbol: "K*⁻", spin: 1, isospin: [], hypercharge: -1, chirality_pct : null, fill_color: "#ADFF2F",  name: "KaonStarMinus", antiparticle: "KaonStarPlus", hadron: ["Strange","AntiUp"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: 1.3e-23, charge: -1, mass: 891.7, baryon: 0, lepton: {e:0,m:0,t:0}},
        KaonStar:      { symbol: "K*⁰", spin: 1, isospin: [], hypercharge: 1, chirality_pct : null, fill_color: "#7FFF00",  name: "KaonStar", antiparticle: "KaonStar", hadron: ["Down","AntiStrange"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: 1.3e-23, charge: 0, mass: 895.8, baryon: 0, lepton: {e:0,m:0,t:0}},
        DMesonStarPlus: { symbol: "D*⁺", spin: 1, isospin: [], hypercharge: 1, chirality_pct : null, fill_color: "#3CB371",  name: "DMesonStarPlus", antiparticle: "DMesonStarMinus", hadron: ["Charm","AntiDown"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: 6.9e-21, charge: 1, mass: 2010.3, baryon: 0, lepton: {e:0,m:0,t:0}},
        DMesonStarMinus: { symbol: "D*⁻", spin: 1, isospin: [], hypercharge: -1, chirality_pct : null, fill_color: "#2E8B57",  name: "DMesonStarMinus", antiparticle: "DMesonStarPlus", hadron: ["Down","AntiCharm"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: 6.9e-21, charge: -1, mass: 2010.3, baryon: 0, lepton: {e:0,m:0,t:0}},
        DMesonStar:    { symbol: "D*⁰", spin: 1, isospin: [], hypercharge: 1, chirality_pct : null, fill_color: "#00FA9A",  name: "DMesonStar", antiparticle: "DMesonStar", hadron: ["Charm","AntiUp"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: 3.1e-22, charge: 0, mass: 2007.0, baryon: 0, lepton: {e:0,m:0,t:0}},
        DsMesonStarPlus: { symbol: "D*_s⁺", spin: 1, isospin: [], hypercharge: 0, chirality_pct : null, fill_color: "#20B2AA",  name: "DsMesonStarPlus", antiparticle: "DsMesonStarMinus", hadron: ["Charm","AntiStrange"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: 3.4e-22, charge: 1, mass: 2112.3, baryon: 0, lepton: {e:0,m:0,t:0}},
        DsMesonStarMinus: { symbol: "D*_s⁻", spin: 1, isospin: [], hypercharge: 0, chirality_pct : null, fill_color: "#5F9EA0",  name: "DsMesonStarMinus", antiparticle: "DsMesonStarPlus", hadron: ["Strange","AntiCharm"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: 3.4e-22, charge: -1, mass: 2112.3, baryon: 0, lepton: {e:0,m:0,t:0}},
        BMesonStarPlus: { symbol: "B*⁺", spin: 1, isospin: [], hypercharge: -1, chirality_pct : null, fill_color: "#CD853F",  name: "BMesonStarPlus", antiparticle: "BMesonStarMinus", hadron: ["Up","AntiBottom"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: null, charge: 1, mass: 5325.2, baryon: 0, lepton: {e:0,m:0,t:0}},
        BMesonStarMinus: { symbol: "B*⁻", spin: 1, isospin: [], hypercharge: 1, chirality_pct : null, fill_color: "#DEB887",  name: "BMesonStarMinus", antiparticle: "BMesonStarPlus", hadron: ["Bottom","AntiUp"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: null, charge: -1, mass: 5325.2, baryon: 0, lepton: {e:0,m:0,t:0}},
        BMesonStar:   { symbol: "B*⁰", spin: 1, isospin: [], hypercharge: -1, chirality_pct : null, fill_color: "#B8860B",  name: "BMesonStar", antiparticle: "BMesonStar", hadron: ["Down","AntiBottom"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: null, charge: 0, mass: 5325.2, baryon: 0, lepton: {e:0,m:0,t:0}},
        BsMesonStar:  { symbol: "B*_s⁰", spin: 1, isospin: [], hypercharge: 0, chirality_pct : null, fill_color: "#FFD700",  name: "BsMesonStar", antiparticle: "BsMesonStar", hadron: ["Strange","AntiBottom"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: null, charge: 0, mass: 5415.4, baryon: 0, lepton: {e:0,m:0,t:0}},
        BcMesonPlus:  { symbol: "B_c⁺", spin: 0, isospin: [], hypercharge: 0, chirality_pct : null, fill_color: "#DAA520",  name: "BcMesonPlus", antiparticle: "BcMesonMinus", hadron: ["Charm","AntiBottom"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: 0.510e-12, charge: 1, mass: 6274.9, baryon: 0, lepton: {e:0,m:0,t:0}},
        BcMesonMinus: { symbol: "B_c⁻", spin: 0, isospin: [], hypercharge: 0, chirality_pct : null, fill_color: "#BDB76B",  name: "BcMesonMinus", antiparticle: "BcMesonPlus", hadron: ["Bottom","AntiCharm"], generation: null,  parity: -1, C_parity: null, G_parity: null, magnetic_moment: 0,  base_lifespan: 0.510e-12, charge: -1, mass: 6274.9, baryon: 0, lepton: {e:0,m:0,t:0}}
        
        Pc4312:      { name:"Pc4312",      symbol:"Pc⁺(4312)", spin:1/2, isospin:[], hypercharge:1,  chirality_pct : null, fill_color:"#cc6699", antiparticle:"AntiPc4312",   hadron:["Up","Up","Down","Charm","AntiCharm"],   generation:null, parity:1,  C_parity:null, G_parity:null, magnetic_moment:0, base_lifespan:1e-23, charge:1,  mass:4312, baryon:1, lepton:{e:0,m:0,t:0} },
        AntiPc4312:  { name:"AntiPc4312",  symbol:"Pc⁻(4312)", spin:1/2, isospin:[], hypercharge:-1, chirality_pct : null, fill_color:"#9966cc", antiparticle:"Pc4312",        hadron:["AntiUp","AntiUp","AntiDown","AntiCharm","Charm"], generation:null, parity:1,  C_parity:null, G_parity:null, magnetic_moment:0, base_lifespan:1e-23, charge:-1, mass:4312, baryon:-1, lepton:{e:0,m:0,t:0} },
        Pc4380:      { name:"Pc4380",      symbol:"Pc⁺(4380)", spin:3/2, isospin:[], hypercharge:1,  chirality_pct : null, fill_color:"#cc6699", antiparticle:"AntiPc4380",   hadron:["Up","Up","Down","Charm","AntiCharm"],   generation:null, parity:-1, C_parity:null, G_parity:null, magnetic_moment:0, base_lifespan:1e-23, charge:1,  mass:4380, baryon:1, lepton:{e:0,m:0,t:0} },
        AntiPc4380:  { name:"AntiPc4380",  symbol:"Pc⁻(4380)", spin:3/2, isospin:[], hypercharge:-1, chirality_pct : null, fill_color:"#9966cc", antiparticle:"Pc4380",        hadron:["AntiUp","AntiUp","AntiDown","AntiCharm","Charm"], generation:null, parity:-1, C_parity:null, G_parity:null, magnetic_moment:0, base_lifespan:1e-23, charge:-1, mass:4380, baryon:-1, lepton:{e:0,m:0,t:0} },
        Pc4440:      { name:"Pc4440",      symbol:"Pc⁺(4440)", spin:1/2, isospin:[], hypercharge:1,  chirality_pct : null, fill_color:"#cc6699", antiparticle:"AntiPc4440",   hadron:["Up","Up","Down","Charm","AntiCharm"],   generation:null, parity:1,  C_parity:null, G_parity:null, magnetic_moment:0, base_lifespan:1e-23, charge:1,  mass:4440, baryon:1, lepton:{e:0,m:0,t:0} },
        AntiPc4440:  { name:"AntiPc4440",  symbol:"Pc⁻(4440)", spin:1/2, isospin:[], hypercharge:-1, chirality_pct : null, fill_color:"#9966cc", antiparticle:"Pc4440",        hadron:["AntiUp","AntiUp","AntiDown","AntiCharm","Charm"], generation:null, parity:1,  C_parity:null, G_parity:null, magnetic_moment:0, base_lifespan:1e-23, charge:-1, mass:4440, baryon:-1, lepton:{e:0,m:0,t:0} },
        Pc4457:      { name:"Pc4457",      symbol:"Pc⁺(4457)", spin:3/2, isospin:[], hypercharge:1,  chirality_pct : null, fill_color:"#cc6699", antiparticle:"AntiPc4457",   hadron:["Up","Up","Down","Charm","AntiCharm"],   generation:null, parity:-1, C_parity:null, G_parity:null, magnetic_moment:0, base_lifespan:1e-23, charge:1,  mass:4457, baryon:1, lepton:{e:0,m:0,t:0} },
        AntiPc4457:  { name:"AntiPc4457",  symbol:"Pc⁻(4457)", spin:3/2, isospin:[], hypercharge:-1, chirality_pct : null, fill_color:"#9966cc", antiparticle:"Pc4457",        hadron:["AntiUp","AntiUp","AntiDown","AntiCharm","Charm"], generation:null, parity:-1, C_parity:null, G_parity:null, magnetic_moment:0, base_lifespan:1e-23, charge:-1, mass:4457, baryon:-1, lepton:{e:0,m:0,t:0} },
        Pcs4459:     { name:"Pcs4459",     symbol:"Pcs⁰(4459)", spin:1/2, isospin:[], hypercharge:0,  chirality_pct : null, fill_color:"#9966cc", antiparticle:"AntiPcs4459",   hadron:["Up","Down","Strange","Charm","AntiCharm"], generation:null, parity:1,  C_parity:null, G_parity:null, magnetic_moment:0, base_lifespan:1e-23, charge:0,  mass:4459, baryon:1, lepton:{e:0,m:0,t:0} },
        AntiPcs4459: { name:"AntiPcs4459", symbol:"Pcs⁰(4459)", spin:1/2, isospin:[], hypercharge:0,  chirality_pct : null, fill_color:"#cc6699", antiparticle:"Pcs4459",        hadron:["AntiUp","AntiDown","AntiStrange","AntiCharm","Charm"], generation:null, parity:1,  C_parity:null, G_parity:null, magnetic_moment:0, base_lifespan:1e-23, charge:0,  mass:4459, baryon:-1, lepton:{e:0,m:0,t:0} } 
    };

    static CalcIsoSpin(particle){
        let I = 0, I3 = 1, T = 2, T3L = 3, T3R = 4;
        let total_isospin = [0,0,0,0,0];
        if(particle.hadron.length > 0){
            let num_hadrons = particle.hadron.length;
            for(let h = 0; h < num_hadrons; h++){
                let iso = Constants.ParticleInfo[particle.hadron[h]].isospin;
                total_isospin[I] += iso[I];
                total_isospin[I3] += iso[I3];
                total_isospin[T] += iso[T];
                total_isospin[T3L] += iso[T3L];
                total_isospin[T3R] += iso[T3R];
            }
            particle.isospin = total_isospin;
        }
        return particle.isospin;
    }

    static GetParticleInfo(type){
        let particle_info = Object.assign({}, Constants.ParticleInfo[type]);
        if(particle_info){
            if(particle_info.isospin.length === 0){
                particle_info.isospin = Constants.CalcIsoSpin(particle_info);
            }
            
            let cpct = particle_info.chirality_pct || Math.random(); // if at random we will need its quarks to add up to this value
            let a = cpct * Math.random();
            let b = (1-cpct) * Math.random();
            particle_info.chirality =  (a / (a+b)) + 1e30;
            particle_info.lifespan = particle_info.base_lifespan / (this.chirality ** 2);
            particle_info.chirality_int = ( particle_info.chirality < .5 ) ? 1 : -1;   
                
            
            particle_info.helicity_handed = 
        }
    }
        
        
}
